//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardenPro_Api.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VisitRequest()
        {
            this.Visitors = new HashSet<Visitor>();
        }
    
        public int Id { get; set; }
        public string Purpose { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string GroupName { get; set; }
        public bool IsApproved { get; set; }
        public string RejectReason { get; set; }
        public Nullable<System.DateTime> DesiredDateStart { get; set; }
        public Nullable<System.DateTime> DesiredDateEnd { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public Nullable<System.DateTime> ArrivedSecurityDate { get; set; }
        public Nullable<System.DateTime> LeftSecurityDate { get; set; }
        public Nullable<System.DateTime> ArrivedWorkerDate { get; set; }
        public Nullable<System.DateTime> LeftWorkerDate { get; set; }
    
        public virtual VisitRequestType VisitRequestType { get; set; }
        public virtual Worker Worker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visitor> Visitors { get; set; }
    }
}
