//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardenPro_Api.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorBlackList
    {
        public int VisitorId { get; set; }
        public string Reason { get; set; }
    
        public virtual Visitor Visitor { get; set; }
    }
}
